# Generated by Django 5.2.7 on 2025-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('webdev', 'Web Development'), ('design', 'Graphic Design'), ('writing', 'Writing/Translation'), ('marketing', 'Digital Marketing'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Comma-separated list of required skills (e.g., Python,React,CSS)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
