# Generated by Django 5.2.7 on 2025-10-21 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_category_project_skills_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Your proposed bid amount for the project.', max_digits=10)),
                ('proposal', models.TextField(help_text='Explain why you are a good fit for this project.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(limit_choices_to={'role': 'FREELANCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
