# Generated by Django 5.2.7 on 2025-10-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skill_user_bio_user_profile_picture_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(blank=True, choices=[('available', 'Available for Hire'), ('busy', 'Currently Busy'), ('not_available', 'Not Available')], default='available', help_text='Your current availability status.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your hourly rate in USD (optional).', max_digits=10, null=True),
        ),
    ]
