# Generated by Django 5.2.7 on 2025-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_availability_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
