# Generated by Django 5.2.7 on 2025-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
    ]
