# Generated by Django 5.2.7 on 2025-11-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_file',
            field=models.FileField(blank=True, help_text='File submitted by the freelancer (e.g., .zip, .pdf)', null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_notes',
            field=models.TextField(blank=True, help_text="Freelancer's notes for the submission."),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
